[package]
name = "heycode-settings"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
heycode-core = { workspace = true }
heycode-doctor = { workspace = true }
async-trait = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio-util = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }

[lints]
workspace = true
