[package]
name = "heycode-http"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
heycode-core = { workspace = true }
futures = { workspace = true }
httpdate = { workspace = true }
reqwest = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["net"] }

[lints]
workspace = true
