[package]
name = "heycode-provider-google"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
heycode-core = { workspace = true }
heycode-llm = { workspace = true }
heycode-authorization = { workspace = true }
heycode-authorization-api-key = { workspace = true }
heycode-http = { workspace = true }
heycode-credentials = { workspace = true }
heycode-authorization-gcp = { workspace = true }
heycode-native-tools = { workspace = true }
heycode-settings = { workspace = true }
async-trait = { workspace = true }
futures = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }

[lints]
workspace = true
