//! Provider-owned Anthropic inference wiring and thinking-state policy.
//!
//! PAN01 shipped identity, auth and discovery but nothing that could dispatch.
//! PAN02 adds the route over the reusable `AnthropicMessagesAdapter` that P05
//! owns, and the requirement that route enforces on replay: an assistant turn
//! waiting on client tool results must come back carrying its own thinking
//! blocks, signatures intact.
//!
//! The rules encoded here are quoted from the vendor documentation rather than
//! inferred:
//!
//! * "when you return tool results, you must pass the thinking blocks from the
//!   assistant message back to the API, complete and unmodified"
//!   <https://platform.claude.com/docs/en/build-with-claude/thinking#thinking-with-tool-use>
//! * "Required: within a tool-use turn, pass thinking blocks back. Recommended:
//!   across turns, pass everything back. Allowed: outside tool use, omit prior
//!   turns' thinking."
//!   <https://platform.claude.com/docs/en/build-with-claude/thinking#preserving-thinking-blocks>
//! * "Full thinking content is encrypted and returned in the `signature` field
//!   on each thinking block. The API uses the signature to verify that thinking
//!   blocks were generated by Claude when you pass them back."
//!   <https://platform.claude.com/docs/en/build-with-claude/thinking#thinking-encryption>
//! * "In extended (manual) mode, the API additionally enforces that the final
//!   assistant turn of a thinking-enabled request begins with a thinking block.
//!   Adaptive mode relaxes this."
//!   <https://platform.claude.com/docs/en/build-with-claude/thinking#thinking-with-tool-use>
//!
//! The failure this row exists to prevent is silent: a mid-turn thinking
//! mismatch is not an error. "If you toggle thinking mid-turn (for example,
//! between sending a tool call and returning its result), the API doesn't
//! error. Instead, it silently disables thinking for that request." Enforcing
//! locally turns an invisible quality regression into a loud local failure with
//! no request bytes sent.

use std::sync::Arc;

use futures::StreamExt as _;
use heycode_core::{ProviderRequestOption, TokenUsage};
use heycode_http::HttpService;
use heycode_llm::{
    AnthropicMessagesAdapter, AnthropicMessagesConfig, AnthropicThinkingMode, CallPurpose,
    ChatRequest, ChunkStream, FinishReason, InferenceAdapter, InferenceEvent, InferenceInput,
    InferenceStream, LlmError, ModelDescriptor, NativeCompactionAdapter,
    NativeCompactionCheckpoint, NativeCompactionError, NativeCompactionFuture, NativeFeature,
    Provider, ProviderErrorClass, ProviderInfo, ProviderOptionContext, ReasoningEffortId,
    RequestDraft, ResolveError, ResolvedCall, RetrySafety, Role, RouteCredential, resolve_request,
};

use crate::catalog::{ANTHROPIC_PROVIDER, DEFAULT_BASE_URL, provider_descriptor};
use crate::response_metadata::ResponseMetadataLedger;
use crate::wire::{
    AnthropicOperationTransport, AnthropicWirePolicy, ObservedResponse, ObservedResponseState,
};
use crate::{
    ANTHROPIC_API_KEY_REFERENCE, ANTHROPIC_CLAUDE_OPUS_5, ANTHROPIC_CONTEXT_EDITING_OPTION_KIND,
    ANTHROPIC_PROMPT_CACHE_OPTION_KIND, ANTHROPIC_VERSION, AnthropicCacheUsage,
    AnthropicCompactionCheckpoint, AnthropicCompactionDefinition, AnthropicCompactionFault,
    AnthropicContextEditReport, AnthropicContextEditingPolicy, AnthropicPromptCachePolicy,
    AnthropicResponseMetadata, AnthropicServerToolFault, AnthropicServerToolKind,
    AnthropicServerToolPlan, anthropic_context_editing_support,
};

/// Beta header that enables interleaved thinking in manual extended-thinking
/// mode.
///
/// It is a manual-mode artifact only. "With adaptive thinking, interleaved
/// thinking is automatic on every model that supports adaptive thinking. No
/// beta header is needed", so [`AnthropicProvider::new`] does not send it —
/// sending an unnecessary beta header would state a requirement the route does
/// not have.
/// <https://platform.claude.com/docs/en/build-with-claude/extended-thinking#interleaved-thinking>
pub const INTERLEAVED_THINKING_BETA: &str = "interleaved-thinking-2025-05-14";

/// Canonical reasoning effort ids this route accepts, in display order.
///
/// `none` disables thinking; the rest are the documented `output_config.effort`
/// levels, sent verbatim.
/// <https://platform.claude.com/docs/en/build-with-claude/effort>
///
/// The list is route-level, not model-level: the Models API publishes
/// `thinking: {supported}` and no effort inventory, so a model that lacks
/// `xhigh` or `max` rejects those levels at the API rather than here.
pub const ANTHROPIC_REASONING_EFFORTS: [&str; 6] =
    ["none", "low", "medium", "high", "xhigh", "max"];

/// Canonical effort used when a caller requests none.
///
/// "Setting `effort` to `"high"` produces exactly the same behavior as omitting
/// the `effort` parameter entirely."
/// <https://platform.claude.com/docs/en/build-with-claude/effort>
pub const ANTHROPIC_DEFAULT_REASONING_EFFORT: &str = "high";

/// What a Messages route requires of a replayed assistant turn that is waiting
/// on client tool results.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum AnthropicThinkingContinuation {
    /// Adaptive thinking. The continued turn must be same-route provider state
    /// carrying whatever thinking the model produced; the model is allowed to
    /// have produced none, because "when the model skips thinking for a simple
    /// request, no thinking block is produced".
    Adaptive,
    /// Manual extended thinking. Everything [`Self::Adaptive`] requires, plus
    /// the documented manual-mode rule that the continued turn must *begin*
    /// with a thinking block.
    Manual,
}

/// The official Anthropic route: a Messages adapter plus provider identity.
pub struct AnthropicProvider {
    adapter: AnthropicMessagesAdapter,
    config: AnthropicMessagesConfig,
    http: HttpService,
    default_model: String,
    continuation: AnthropicThinkingContinuation,
    thinking_efforts: Vec<ReasoningEffortId>,
    compaction: AnthropicCompactionDefinition,
    context_editing: Option<AnthropicContextEditingPolicy>,
    prompt_cache: Option<AnthropicPromptCachePolicy>,
    server_tools: Option<AnthropicServerToolPlan>,
    request_options: Vec<ProviderRequestOption>,
    response_metadata: ResponseMetadataLedger,
}

impl AnthropicProvider {
    /// Build the official adaptive-thinking route against the Anthropic API
    /// origin.
    ///
    /// Adaptive is the only correct dialect for the provider default model:
    /// `thinking: {"type":"enabled"}` "return[s] a 400 error" on Claude Opus
    /// 4.7 and later, which includes `claude-opus-5`.
    /// <https://platform.claude.com/docs/en/build-with-claude/extended-thinking>
    ///
    /// # Errors
    /// An unusable endpoint, an empty key or an invalid effort mapping fails
    /// before the route is published.
    pub fn new(
        http: HttpService,
        api_key: impl Into<String>,
        default_model: Option<String>,
    ) -> Result<Self, LlmError> {
        Self::with_base_url(http, DEFAULT_BASE_URL, api_key, default_model)
    }

    /// Build the adaptive-thinking route against an explicit Anthropic-
    /// compatible API base URL.
    ///
    /// # Errors
    /// Same contract as [`Self::new`].
    pub fn with_base_url(
        http: HttpService,
        base_url: impl AsRef<str>,
        api_key: impl Into<String>,
        default_model: Option<String>,
    ) -> Result<Self, LlmError> {
        Self::with_base_url_and_credential(
            http,
            base_url,
            RouteCredential::fixed(api_key),
            default_model,
        )
    }

    /// Build the official adaptive-thinking route with one operation-time
    /// credential binding.
    ///
    /// # Errors
    /// Same contract as [`Self::new`].
    pub fn with_credential(
        http: HttpService,
        credential: RouteCredential,
        default_model: Option<String>,
    ) -> Result<Self, LlmError> {
        Self::with_base_url_and_credential(http, DEFAULT_BASE_URL, credential, default_model)
    }

    /// Build an explicit-base adaptive-thinking route with one operation-time
    /// credential binding.
    ///
    /// # Errors
    /// Same contract as [`Self::new`].
    pub fn with_base_url_and_credential(
        http: HttpService,
        base_url: impl AsRef<str>,
        credential: RouteCredential,
        default_model: Option<String>,
    ) -> Result<Self, LlmError> {
        let modes = ANTHROPIC_REASONING_EFFORTS
            .iter()
            .map(|effort| {
                let id = ReasoningEffortId::new(*effort).map_err(resolve_to_llm)?;
                // `none` carries no `output_config.effort`: sending one
                // alongside `thinking: {"type":"disabled"}` is what makes the
                // documented Opus 5 rejection at `xhigh`/`max` reachable, and
                // omitting it leaves the API default (`high`) in place.
                let mode = if *effort == "none" {
                    AnthropicThinkingMode::disabled()
                } else {
                    AnthropicThinkingMode::adaptive(None).with_wire_effort(*effort)
                };
                Ok((id, mode))
            })
            .collect::<Result<Vec<_>, LlmError>>()?;
        Self::build(
            http,
            base_url,
            credential,
            default_model,
            modes,
            Vec::new(),
            AnthropicThinkingContinuation::Adaptive,
        )
    }

    /// Build a manual extended-thinking route for the models that support only
    /// that dialect (Claude Sonnet 4.5, Claude Opus 4.5, Claude Haiku 4.5 and
    /// earlier Claude 4 models), with interleaved thinking requested.
    ///
    /// No `output_config.effort` is sent: effort is unsupported on most of that
    /// lineup, so this route controls depth with `budget_tokens` alone.
    ///
    /// `budget_tokens` must be at least 1024 and stay below the effective
    /// output cap. The route deliberately does not claim the interleaved budget
    /// exemption — "Claude Haiku 4.5 does not support interleaved thinking",
    /// and the header is accepted-and-ignored there, so a budget at or above
    /// `max_tokens` would be rejected on a model this same route serves.
    /// <https://platform.claude.com/docs/en/build-with-claude/extended-thinking#budget-rules-and-tuning>
    ///
    /// # Errors
    /// Same contract as [`Self::new`]; the manual route additionally requires
    /// an explicit model and rejects the known adaptive-only provider default.
    /// The caller remains responsible for selecting another model that accepts
    /// manual interleaved thinking. A budget below 1024 tokens is rejected by
    /// the adapter.
    pub fn extended_thinking(
        http: HttpService,
        base_url: impl AsRef<str>,
        api_key: impl Into<String>,
        default_model: Option<String>,
        budget_tokens: u64,
    ) -> Result<Self, LlmError> {
        let default_model = default_model
            .filter(|model| !model.trim().is_empty() && model != ANTHROPIC_CLAUDE_OPUS_5)
            .ok_or_else(|| {
                LlmError::InvalidResponse(
                    "manual thinking model must be explicitly configured and compatible".to_owned(),
                )
            })?;
        let none = ReasoningEffortId::new("none").map_err(resolve_to_llm)?;
        let high =
            ReasoningEffortId::new(ANTHROPIC_DEFAULT_REASONING_EFFORT).map_err(resolve_to_llm)?;
        Self::build(
            http,
            base_url,
            RouteCredential::fixed(api_key),
            Some(default_model),
            vec![
                (none, AnthropicThinkingMode::disabled()),
                (high, AnthropicThinkingMode::enabled(budget_tokens, None)),
            ],
            vec![(
                "anthropic-beta".to_owned(),
                INTERLEAVED_THINKING_BETA.to_owned(),
            )],
            AnthropicThinkingContinuation::Manual,
        )
    }

    fn build(
        http: HttpService,
        base_url: impl AsRef<str>,
        credential: RouteCredential,
        default_model: Option<String>,
        modes: Vec<(ReasoningEffortId, AnthropicThinkingMode)>,
        extra_headers: Vec<(String, String)>,
        continuation: AnthropicThinkingContinuation,
    ) -> Result<Self, LlmError> {
        let base_url = format!("{}/v1", base_url.as_ref().trim_end_matches('/'));
        let default_effort =
            ReasoningEffortId::new(ANTHROPIC_DEFAULT_REASONING_EFFORT).map_err(resolve_to_llm)?;
        let thinking_efforts = modes
            .iter()
            .filter(|(_, mode)| !matches!(mode, AnthropicThinkingMode::Disabled { .. }))
            .map(|(effort, _)| effort.clone())
            .collect();
        let config =
            AnthropicMessagesConfig::with_credential(provider_descriptor(), base_url, credential)
                .with_anthropic_version(Some(ANTHROPIC_VERSION.to_owned()))
                .with_extra_headers(extra_headers)
                .with_externally_consumed_provider_option_kind(
                    ANTHROPIC_CONTEXT_EDITING_OPTION_KIND,
                )
                .with_externally_consumed_provider_option_kind(ANTHROPIC_PROMPT_CACHE_OPTION_KIND)
                .with_thinking(modes, Some(default_effort));
        let adapter = AnthropicMessagesAdapter::new(config.clone(), http.clone())?;
        let compaction = AnthropicCompactionDefinition::new(None, true)
            .map_err(|error| LlmError::InvalidResponse(error.to_string()))?;
        Ok(Self {
            adapter,
            config,
            http,
            default_model: default_model.unwrap_or_else(|| ANTHROPIC_CLAUDE_OPUS_5.to_owned()),
            continuation,
            thinking_efforts,
            compaction,
            context_editing: None,
            prompt_cache: None,
            server_tools: None,
            request_options: Vec::new(),
            response_metadata: ResponseMetadataLedger::default(),
        })
    }

    /// Replay requirement this route enforces on a thinking tool continuation.
    #[must_use]
    pub const fn continuation(&self) -> AnthropicThinkingContinuation {
        self.continuation
    }

    /// Attach an exact server-side context-editing policy to every normal
    /// Messages request.
    ///
    /// # Errors
    /// The policy must enter the durable provider-option plane unchanged.
    pub fn with_context_editing(
        mut self,
        policy: AnthropicContextEditingPolicy,
    ) -> Result<Self, LlmError> {
        let option = policy
            .provider_option()
            .map_err(|error| LlmError::InvalidResponse(error.to_string()))?;
        self.context_editing = Some(policy);
        self.replace_request_option(option);
        Ok(self)
    }

    /// Attach top-level automatic prompt caching to every Messages request.
    ///
    /// # Errors
    /// The policy must enter the durable provider-option plane unchanged.
    pub fn with_prompt_caching(
        mut self,
        policy: AnthropicPromptCachePolicy,
    ) -> Result<Self, LlmError> {
        let option = policy
            .provider_option()
            .map_err(|error| LlmError::InvalidResponse(error.to_string()))?;
        self.prompt_cache = Some(policy);
        self.replace_request_option(option);
        Ok(self)
    }

    /// Attach one exact provider-gated server-tool plan to ordinary Messages
    /// requests and the generic Messages parser.
    ///
    /// The plan remains provider-owned for model/pair evidence, while the
    /// reusable adapter owns request serialization, call/result correlation,
    /// normalized events and lossless provider state.
    ///
    /// # Errors
    /// Invalid generic plan configuration or a provider option that cannot
    /// enter the durable request plane fails before provider publication.
    pub fn with_server_tools(mut self, plan: AnthropicServerToolPlan) -> Result<Self, LlmError> {
        let messages_plan = plan
            .messages_plan_unchecked()
            .map_err(server_tool_configuration_error)?;
        plan.provider_option()
            .map_err(server_tool_configuration_error)?;
        let config = self.config.clone().with_server_tool_plan(messages_plan);
        let adapter = AnthropicMessagesAdapter::new(config.clone(), self.http.clone())?;
        self.config = config;
        self.adapter = adapter;
        self.server_tools = Some(plan);
        Ok(self)
    }

    /// Remove the live server-tool selection while retaining registered replay
    /// routes and beta knowledge for already-completed historical blocks.
    ///
    /// A pending server call still fails shared resolution without its exact
    /// option, which prevents this history-only hook from dropping the tool
    /// definition required to resume `pause_turn`.
    #[must_use]
    pub fn without_server_tool_selection(mut self) -> Self {
        self.server_tools = None;
        self.request_options
            .retain(|option| option.kind() != crate::ANTHROPIC_SERVER_TOOLS_OPTION_KIND);
        self
    }

    /// Replace the default pause-producing native compaction definition.
    #[must_use]
    pub fn with_compaction_definition(mut self, definition: AnthropicCompactionDefinition) -> Self {
        self.compaction = definition;
        self
    }

    /// Take one successful response's provider-specific metadata.
    ///
    /// Metadata publishes only after the normalized stream reaches Finish and
    /// is retained under the provider response id with a fixed bound.
    #[must_use]
    pub fn take_response_metadata(&self, response_id: &str) -> Option<AnthropicResponseMetadata> {
        self.response_metadata.take(response_id)
    }

    fn replace_request_option(&mut self, option: ProviderRequestOption) {
        self.request_options
            .retain(|current| current.kind() != option.kind());
        self.request_options.push(option);
        self.request_options
            .sort_by(|left, right| left.kind().cmp(right.kind()));
    }

    fn expected_request_options(
        &self,
        model: &ModelDescriptor,
        routes: &[heycode_core::NativeToolRoute],
    ) -> Result<Vec<ProviderRequestOption>, ResolveError> {
        let mut options = self.request_options.clone();
        match &self.server_tools {
            Some(plan) => {
                if let Some(option) = plan
                    .provider_option_for_routes(&model.id, routes)
                    .map_err(|error| server_tool_resolve_error(error, &model.id))?
                {
                    options.retain(|current| current.kind() != option.kind());
                    options.push(option);
                    options.sort_by(|left, right| left.kind().cmp(right.kind()));
                }
            }
            None if routes.iter().any(is_anthropic_server_tool_route) => {
                return Err(server_tool_resolve_error(
                    AnthropicServerToolFault::InvalidConfiguration,
                    &model.id,
                ));
            }
            None => {}
        }
        Ok(options)
    }

    /// Whether the resolved call actually turned thinking on.
    fn thinking_is_on(&self, call: &ResolvedCall) -> bool {
        call.reasoning_effort()
            .is_some_and(|effort| self.thinking_efforts.iter().any(|known| known == effort))
    }

    /// Reject a replay that cannot satisfy the documented thinking contract.
    ///
    /// Resolution runs before transport, so a rejection here costs no request
    /// bytes.
    fn validate_thinking_continuation(&self, call: &ResolvedCall) -> Result<(), ResolveError> {
        // Signature integrity is unconditional. A thinking block whose
        // signature was dropped by a re-serializer, a truncated log or a
        // hand-built item is corrupt whether or not this request enables
        // thinking, and this route's own parser can never produce one.
        for input in call.inputs() {
            if let InferenceInput::ProviderState(state) = input {
                for block in state_content(state) {
                    validate_thinking_integrity(block)?;
                }
            }
        }
        if !self.thinking_is_on(call) {
            return Ok(());
        }
        if self.continuation == AnthropicThinkingContinuation::Manual
            && call.model() == ANTHROPIC_CLAUDE_OPUS_5
        {
            return Err(invalid_state(
                "manual thinking model is incompatible with adaptive-only Claude Opus 5",
            ));
        }
        // "Allowed: outside tool use, omit prior turns' thinking." Only the
        // current turn carries the requirement, and the turn begins at the most
        // recent standard user message — a tool result continues the turn it
        // belongs to rather than starting a new one.
        for input in &call.inputs()[current_turn_start(call.inputs())..] {
            match input {
                // A neutral assistant message has no field that can carry a
                // thinking block, so it cannot satisfy the contract; the
                // adapter would serialize a bare `tool_use` array and the API
                // would silently drop thinking for the turn. Same-route
                // provider state is the only shape that can replay it.
                InferenceInput::Message(message)
                    if message.role == Role::Assistant
                        && message
                            .tool_calls
                            .as_ref()
                            .is_some_and(|calls| !calls.is_empty()) =>
                {
                    return Err(invalid_state(
                        "Messages thinking tool continuation requires same-route provider state; a neutral assistant message cannot carry its thinking blocks",
                    ));
                }
                InferenceInput::ProviderState(state)
                    if self.continuation == AnthropicThinkingContinuation::Manual
                        && state_content(state)
                            .iter()
                            .any(|block| block_type(block) == Some("tool_use")) =>
                {
                    // Manual mode only: the continued turn must *begin* with a
                    // thinking block. `redacted_thinking` counts, because
                    // filtering it out "breaks the multi-turn protocol".
                    if !state_content(state)
                        .first()
                        .and_then(block_type)
                        .is_some_and(is_thinking_block)
                    {
                        return Err(invalid_state(
                            "manual extended thinking requires the continued assistant turn to begin with a thinking block",
                        ));
                    }
                }
                InferenceInput::Message(_) | InferenceInput::ProviderState(_) => {}
            }
        }
        Ok(())
    }
}

fn is_anthropic_server_tool_route(route: &heycode_core::NativeToolRoute) -> bool {
    route.kind() == heycode_core::NativeToolImplementationKind::Provider
        && route.provider() == Some(ANTHROPIC_PROVIDER)
        && AnthropicServerToolKind::ALL
            .iter()
            .any(|kind| kind.as_str() == route.logical())
}

impl Provider for AnthropicProvider {
    fn info(&self) -> ProviderInfo {
        ProviderInfo {
            name: ANTHROPIC_PROVIDER.to_owned(),
            default_model: self.default_model.clone(),
        }
    }

    fn credential_reference(&self) -> Option<&str> {
        Some(ANTHROPIC_API_KEY_REFERENCE)
    }

    fn descriptor(&self) -> heycode_llm::ProviderDescriptor {
        provider_descriptor()
    }

    fn inference_adapter(&self) -> Option<&dyn InferenceAdapter> {
        Some(self)
    }

    fn request_options(&self) -> Vec<ProviderRequestOption> {
        self.request_options.clone()
    }

    fn request_options_for(
        &self,
        context: ProviderOptionContext<'_>,
    ) -> Result<Vec<ProviderRequestOption>, ResolveError> {
        self.expected_request_options(context.model(), context.native_tool_routes())
    }

    // No `rate_limit_headers` override: this row proves no header spelling, and
    // declaring an unverified `anthropic-ratelimit-*` name would make `/usage`
    // display a guess.

    fn stream(&self, _request: ChatRequest) -> ChunkStream {
        // This route advertises an inference adapter, so the legacy path must
        // fail loud rather than dispatch a request that bypasses the thinking
        // replay contract above (AGENTS §5).
        Box::pin(futures::stream::once(async {
            Err(LlmError::InvalidResponse(
                "Anthropic route dispatches through its inference adapter; the legacy chat path is not available"
                    .to_owned(),
            ))
        }))
    }
}

impl InferenceAdapter for AnthropicProvider {
    fn descriptor(&self) -> heycode_llm::ProviderDescriptor {
        provider_descriptor()
    }

    fn authentication_binding(&self) -> heycode_llm::AuthenticationBinding {
        self.adapter.authentication_binding()
    }

    fn reasoning_effort_options(
        &self,
        model: &ModelDescriptor,
    ) -> Result<Option<heycode_llm::ReasoningEffortOptions>, ResolveError> {
        self.adapter.reasoning_effort_options(model)
    }

    fn resolve(
        &self,
        mut draft: RequestDraft,
        model: &ModelDescriptor,
    ) -> Result<ResolvedCall, ResolveError> {
        let expected = self.expected_request_options(model, &draft.native_tool_routes)?;
        if draft.provider_options != expected {
            return Err(ResolveError::InvalidRequest {
                field: "provider_options",
                message: "Anthropic provider options differ from the selected model/routes"
                    .to_owned(),
            });
        }
        let provider_web_selected = draft.native_tool_routes.iter().any(|route| {
            route.kind() == heycode_core::NativeToolImplementationKind::Provider
                && route.provider() == Some(ANTHROPIC_PROVIDER)
                && matches!(route.logical(), "web_search" | "web_fetch")
        });
        if provider_web_selected {
            // `server_tool_support` above is the per-model primary-source
            // gate. The authenticated Models endpoint has no native-web field,
            // so retaining the generic feature would ask the common resolver
            // to reinterpret that absent endpoint field as provider evidence.
            // The exact N01 route and provider option remain durable.
            draft
                .native_features
                .retain(|feature| *feature != NativeFeature::Web);
        }
        if self.prompt_cache.is_some()
            && !draft.native_features.contains(&NativeFeature::PromptCache)
        {
            draft.native_features.push(NativeFeature::PromptCache);
        }
        let native_compaction = draft.native_features.contains(&NativeFeature::Compaction);
        if native_compaction && draft.purpose != CallPurpose::Compaction {
            return Err(ResolveError::InvalidRequest {
                field: "native_features",
                message: "Anthropic Compaction is reserved for CallPurpose::Compaction".to_owned(),
            });
        }
        if self.context_editing.is_some() {
            match anthropic_context_editing_support(&model.id) {
                heycode_llm::CapabilitySupport::Supported => {}
                heycode_llm::CapabilitySupport::Unsupported => {
                    return Err(ResolveError::Unsupported {
                        provider: ANTHROPIC_PROVIDER.to_owned(),
                        model: model.id.clone(),
                        capability: heycode_llm::RequestedCapability::NativeCompaction,
                    });
                }
                heycode_llm::CapabilitySupport::Unknown => {
                    return Err(ResolveError::Unproven {
                        provider: ANTHROPIC_PROVIDER.to_owned(),
                        model: model.id.clone(),
                        capability: heycode_llm::RequestedCapability::NativeCompaction,
                    });
                }
            }
        }
        if native_compaction {
            self.compaction
                .request_fields_for(&model.id)
                .map_err(|error| compaction_resolve_error(error, &model.id))?;
        }

        // The shared adapter remains the one Messages structure/thinking/tool
        // validator. Product-only options and native features are removed from
        // this detached validation draft, then the original complete draft is
        // resolved below so C02/C05 retain them exactly.
        let mut validation = draft.clone();
        validation
            .provider_options
            .retain(|option| option.kind() == crate::ANTHROPIC_SERVER_TOOLS_OPTION_KIND);
        validation.native_features.retain(|feature| {
            !matches!(
                feature,
                NativeFeature::Compaction | NativeFeature::PromptCache
            )
        });
        // Messages requires max_tokens. Use a bounded product default when
        // the caller omitted it, clamped to the exact catalog model limit.
        let config = self.config.clone().with_default_max_output_tokens(Some(
            model.max_output_tokens.unwrap_or(8_192).min(8_192),
        ));
        let validation_adapter = AnthropicMessagesAdapter::new(config.clone(), self.http.clone())
            .map_err(|error| ResolveError::InvalidAdapter {
            field: "default_max_output_tokens",
            message: error.to_string(),
        })?;
        let validated = validation_adapter.resolve(validation, model)?;
        draft.temperature = validated.temperature();
        let call = resolve_request(&provider_descriptor(), draft, model, &config.resolve_spec())?;
        self.validate_thinking_continuation(&call)?;
        // `resolve_request` proves replay safety only from native features and
        // provider-executed routes. The Messages adapter additionally withholds
        // it for the protocol evidence it alone reads — a compaction or
        // server-tool block in provider state, a container, a non-direct tool
        // caller, a selected server-tool plan — so the shipped route keeps
        // whichever of the two proofs is narrower. Both specs come from the one
        // `AnthropicMessagesConfig`, so only the safety differs.
        let retry_spec = call.retry_spec().clone().with_safety(narrower_safety(
            validated.retry_spec().safety(),
            call.retry_spec().safety(),
        ));
        Ok(call.with_retry_spec(retry_spec))
    }

    fn stream(&self, call: ResolvedCall) -> InferenceStream {
        self.stream_cancellable(call, tokio_util::sync::CancellationToken::new())
    }

    fn stream_cancellable(
        &self,
        call: ResolvedCall,
        cancellation: tokio_util::sync::CancellationToken,
    ) -> InferenceStream {
        self.operation_stream(call, cancellation)
    }

    fn native_compaction(&self) -> Option<&dyn NativeCompactionAdapter> {
        Some(self)
    }
}

impl AnthropicProvider {
    fn operation_stream(
        &self,
        call: ResolvedCall,
        cancellation: tokio_util::sync::CancellationToken,
    ) -> InferenceStream {
        let is_compaction = call.native_features().contains(&NativeFeature::Compaction);
        let mut request_fields = Vec::new();
        let mut betas = Vec::new();
        if let Some(policy) = &self.context_editing {
            request_fields.push(policy.request_fields().clone());
            betas.extend(
                policy
                    .beta_headers()
                    .iter()
                    .map(|value| (*value).to_owned()),
            );
        }
        if let Some(policy) = &self.prompt_cache {
            request_fields.push(policy.request_fields().clone());
        }
        if is_compaction {
            let fields = match self.compaction.request_fields_for(call.model()) {
                Ok(fields) => fields,
                Err(error) => {
                    return one_inference_error(LlmError::InvalidResponse(error.to_string()));
                }
            };
            request_fields.push(fields);
            betas.extend(
                self.compaction
                    .beta_headers()
                    .iter()
                    .map(|value| (*value).to_owned()),
            );
        }
        if request_fields.is_empty() && betas.is_empty() {
            return InferenceAdapter::stream_cancellable(&self.adapter, call, cancellation);
        }

        let observed = ObservedResponse::default();
        let transport = AnthropicOperationTransport::new(
            self.http.clone(),
            AnthropicWirePolicy::new(request_fields, betas, is_compaction),
            observed.clone(),
        );
        let adapter = match AnthropicMessagesAdapter::new(
            self.config.clone(),
            HttpService::new(Arc::new(transport)),
        ) {
            Ok(adapter) => adapter,
            Err(error) => return one_inference_error(error),
        };
        let stream = InferenceAdapter::stream_cancellable(&adapter, call, cancellation);
        with_response_metadata(
            stream,
            observed,
            self.response_metadata.clone(),
            self.context_editing.is_some(),
            self.prompt_cache.is_some(),
        )
    }
}

impl NativeCompactionAdapter for AnthropicProvider {
    fn compact(
        &self,
        call: ResolvedCall,
        cancellation: tokio_util::sync::CancellationToken,
    ) -> NativeCompactionFuture<'_> {
        Box::pin(async move {
            if cancellation.is_cancelled() {
                return Err(NativeCompactionError::Cancelled);
            }
            if call.purpose() != CallPurpose::Compaction
                || !call.native_features().contains(&NativeFeature::Compaction)
                || call.provider() != ANTHROPIC_PROVIDER
                || call.protocol() != heycode_core::ProviderProtocol::AnthropicMessages
            {
                return Err(NativeCompactionError::InvalidCheckpoint);
            }
            let model = call.model().to_owned();
            let mut stream = self.operation_stream(call, cancellation.clone());
            let mut state = None;
            let mut normalized_usage = None;
            let mut finish = None;
            while let Some(item) = stream.next().await {
                let event =
                    item.map_err(|error| map_native_compaction_error(&error, &cancellation))?;
                match event {
                    InferenceEvent::ProviderState(item) => {
                        if state.replace(item).is_some() {
                            return Err(NativeCompactionError::InvalidCheckpoint);
                        }
                    }
                    InferenceEvent::Usage(usage) => {
                        if normalized_usage.replace(usage).is_some() {
                            return Err(NativeCompactionError::InvalidCheckpoint);
                        }
                    }
                    InferenceEvent::Finish(reason) => finish = Some(reason),
                    InferenceEvent::ResponseStarted { .. }
                    | InferenceEvent::ItemStarted { .. }
                    | InferenceEvent::TextDelta(_)
                    | InferenceEvent::ReasoningDelta(_)
                    | InferenceEvent::ToolCallDelta { .. }
                    | InferenceEvent::ServerToolCall { .. }
                    | InferenceEvent::ServerToolResult { .. }
                    | InferenceEvent::ServerToolUsage(_)
                    | InferenceEvent::Citation { .. }
                    | InferenceEvent::ItemFinished { .. }
                    | InferenceEvent::ResponseMetadata(_)
                    | InferenceEvent::ResponseFinished { .. } => {}
                }
            }
            let expected_finish = if self.compaction.pause_after_compaction() {
                FinishReason::Pause
            } else {
                FinishReason::Stop
            };
            if finish != Some(expected_finish) || normalized_usage.is_none() {
                return Err(NativeCompactionError::InvalidCheckpoint);
            }
            let state = state.ok_or(NativeCompactionError::InvalidCheckpoint)?;
            AnthropicCompactionCheckpoint::from_state(&model, state.clone())
                .map_err(|_| NativeCompactionError::InvalidCheckpoint)?;
            NativeCompactionCheckpoint::new(vec![state], normalized_usage)
        })
    }
}

/// Build the official route behind an `Arc` for registry contribution.
///
/// # Errors
/// Same contract as [`AnthropicProvider::new`].
pub fn anthropic_provider(
    http: HttpService,
    api_key: impl Into<String>,
    default_model: Option<String>,
) -> Result<Arc<dyn Provider>, LlmError> {
    Ok(Arc::new(AnthropicProvider::new(
        http,
        api_key,
        default_model,
    )?))
}

/// The narrower of two replay-safety proofs.
///
/// Replay safety is evidence, never preference: two resolvers that each saw
/// part of the request may only ever agree on the least permissive proof.
fn narrower_safety(left: RetrySafety, right: RetrySafety) -> RetrySafety {
    if replay_rank(left) <= replay_rank(right) {
        left
    } else {
        right
    }
}

/// Order replay safety from the least to the most permissive proof.
const fn replay_rank(safety: RetrySafety) -> u8 {
    match safety {
        RetrySafety::Never => 0,
        RetrySafety::DefinitiveFailuresOnly => 1,
        RetrySafety::StatelessPreOutput => 2,
    }
}

/// Index of the first input belonging to the current assistant turn.
///
/// A tool result is a `user` message on the wire but continues the turn it
/// belongs to, so only a standard user message opens a new one.
fn current_turn_start(inputs: &[InferenceInput]) -> usize {
    inputs
        .iter()
        .rposition(
            |input| matches!(input, InferenceInput::Message(message) if message.role == Role::User),
        )
        .map_or(0, |index| index.saturating_add(1))
}

fn state_content(state: &heycode_core::ProviderStateItem) -> &[serde_json::Value] {
    state
        .data()
        .get("content")
        .and_then(serde_json::Value::as_array)
        .map_or(&[], Vec::as_slice)
}

fn block_type(block: &serde_json::Value) -> Option<&str> {
    block.get("type").and_then(serde_json::Value::as_str)
}

const fn is_thinking_block(block_type: &str) -> bool {
    matches!(block_type.as_bytes(), b"thinking" | b"redacted_thinking")
}

/// Reject a replayed thinking block whose opaque continuity field is gone.
///
/// An empty `thinking` field is legitimate: with `display: "omitted"` the
/// server returns "thinking blocks ... with an empty `thinking` field" while
/// "the `signature` field still carries the encrypted full thinking". Only the
/// opaque field is load-bearing, so only the opaque field is checked.
fn validate_thinking_integrity(block: &serde_json::Value) -> Result<(), ResolveError> {
    let opaque = match block_type(block) {
        Some("thinking") => "signature",
        Some("redacted_thinking") => "data",
        _ => return Ok(()),
    };
    if block
        .get(opaque)
        .and_then(serde_json::Value::as_str)
        .is_none_or(str::is_empty)
    {
        return Err(invalid_state(
            "replayed Messages thinking block lost its opaque continuity field",
        ));
    }
    Ok(())
}

fn invalid_state(message: &str) -> ResolveError {
    ResolveError::InvalidRequest {
        field: "provider_state",
        message: message.to_owned(),
    }
}

struct ResponseMetadataStreamState {
    stream: InferenceStream,
    observed: ObservedResponse,
    ledger: ResponseMetadataLedger,
    expect_context_editing: bool,
    expect_cache_usage: bool,
    response_id: Option<String>,
    pending: Option<AnthropicResponseMetadata>,
    normalized_usage: Option<TokenUsage>,
    queued: Option<InferenceEvent>,
    terminal: bool,
}

fn with_response_metadata(
    stream: InferenceStream,
    observed: ObservedResponse,
    ledger: ResponseMetadataLedger,
    expect_context_editing: bool,
    expect_cache_usage: bool,
) -> InferenceStream {
    if !expect_context_editing && !expect_cache_usage {
        return stream;
    }
    Box::pin(futures::stream::unfold(
        ResponseMetadataStreamState {
            stream,
            observed,
            ledger,
            expect_context_editing,
            expect_cache_usage,
            response_id: None,
            pending: None,
            normalized_usage: None,
            queued: None,
            terminal: false,
        },
        |mut state| async move {
            if state.terminal {
                return None;
            }
            if let Some(event) = state.queued.take() {
                return Some((Ok(event), state));
            }
            let item = state.stream.next().await?;
            let event = match item {
                Ok(event) => event,
                Err(error) => {
                    state.terminal = true;
                    return Some((Err(error), state));
                }
            };
            match &event {
                InferenceEvent::ResponseStarted { response_id } => {
                    state.response_id = Some(response_id.clone());
                }
                InferenceEvent::ProviderState(_) => {
                    let observed = state.observed.snapshot();
                    if observed.response_id != state.response_id {
                        state.terminal = true;
                        return Some((Err(metadata_error()), state));
                    }
                    let metadata = match response_metadata_from_observation(
                        &observed,
                        state.expect_context_editing,
                        state.expect_cache_usage,
                    ) {
                        Ok(metadata) => metadata,
                        Err(error) => {
                            state.terminal = true;
                            return Some((Err(error), state));
                        }
                    };
                    state.pending = Some(metadata);
                }
                InferenceEvent::Usage(usage) => {
                    state.normalized_usage = Some(*usage);
                    let Some(metadata) = state.pending.as_ref() else {
                        state.terminal = true;
                        return Some((Err(metadata_error()), state));
                    };
                    if let Some(cache) = metadata.cache_usage()
                        && (cache.total_input_tokens() != usage.prompt_tokens
                            || cache.output_tokens() != usage.completion_tokens)
                    {
                        state.terminal = true;
                        return Some((Err(metadata_error()), state));
                    }
                    let neutral = match neutral_response_metadata(metadata) {
                        Ok(metadata) => metadata,
                        Err(error) => {
                            state.terminal = true;
                            return Some((Err(error), state));
                        }
                    };
                    state.queued = Some(event);
                    return Some((Ok(InferenceEvent::ResponseMetadata(neutral)), state));
                }
                InferenceEvent::Finish(_) => {
                    let Some(response_id) = state.response_id.clone() else {
                        state.terminal = true;
                        return Some((Err(metadata_error()), state));
                    };
                    let Some(metadata) = state.pending.take() else {
                        state.terminal = true;
                        return Some((Err(metadata_error()), state));
                    };
                    if let Some(cache) = metadata.cache_usage() {
                        let Some(normalized) = state.normalized_usage else {
                            state.terminal = true;
                            return Some((Err(metadata_error()), state));
                        };
                        if cache.total_input_tokens() != normalized.prompt_tokens
                            || cache.output_tokens() != normalized.completion_tokens
                        {
                            state.terminal = true;
                            return Some((Err(metadata_error()), state));
                        }
                    }
                    state.ledger.insert(response_id, metadata);
                    state.terminal = true;
                }
                InferenceEvent::ItemStarted { .. }
                | InferenceEvent::TextDelta(_)
                | InferenceEvent::ReasoningDelta(_)
                | InferenceEvent::ToolCallDelta { .. }
                | InferenceEvent::ServerToolCall { .. }
                | InferenceEvent::ServerToolResult { .. }
                | InferenceEvent::ServerToolUsage(_)
                | InferenceEvent::Citation { .. }
                | InferenceEvent::ItemFinished { .. }
                | InferenceEvent::ResponseFinished { .. } => {}
                InferenceEvent::ResponseMetadata(_) => {
                    state.terminal = true;
                    return Some((Err(metadata_error()), state));
                }
            }
            Some((Ok(event), state))
        },
    ))
}

fn neutral_response_metadata(
    metadata: &AnthropicResponseMetadata,
) -> Result<heycode_core::ProviderResponseMetadata, LlmError> {
    let cache = metadata
        .cache_usage()
        .map(|cache| {
            let usage = heycode_core::ProviderCacheUsage::new(
                cache.total_input_tokens(),
                cache.output_tokens(),
                cache.cache_read_input_tokens(),
                cache.cache_creation_input_tokens(),
            )
            .and_then(|usage| usage.with_uncached_input_tokens(cache.uncached_input_tokens()))?;
            match (
                cache.cache_creation_5m_input_tokens(),
                cache.cache_creation_1h_input_tokens(),
            ) {
                (Some(five), Some(hour)) => usage.with_cache_write_ttl_tokens(five, hour),
                (None, None) => Ok(usage),
                _ => Err(heycode_core::ProviderResponseMetadataError::InvalidCacheUsage),
            }
        })
        .transpose()
        .map_err(|_| metadata_error())?;
    let (edits, impact) = metadata
        .context_editing()
        .map_or_else(
            || Ok((Vec::new(), None)),
            |report| {
                let edits = report
                    .edits()
                    .iter()
                    .map(|edit| {
                        let kind = match edit.kind() {
                            crate::AnthropicContextEditKind::ClearThinking => {
                                heycode_core::ContextEditKind::ClearThinking
                            }
                            crate::AnthropicContextEditKind::ClearToolUses => {
                                heycode_core::ContextEditKind::ClearToolUses
                            }
                        };
                        heycode_core::ProviderContextEdit::new(
                            kind,
                            edit.cleared_units(),
                            edit.cleared_input_tokens(),
                        )
                    })
                    .collect::<Result<Vec<_>, _>>()?;
                let impact = match report.cache_impact() {
                    crate::AnthropicCacheImpact::Preserved => {
                        heycode_core::CachePrefixImpact::Preserved
                    }
                    crate::AnthropicCacheImpact::InvalidatedAtEdit => {
                        heycode_core::CachePrefixImpact::InvalidatedAtEdit
                    }
                };
                Ok((edits, Some(impact)))
            },
        )
        .map_err(|_: heycode_core::ProviderResponseMetadataError| metadata_error())?;
    heycode_core::ProviderResponseMetadata::new(cache, edits, impact).map_err(|_| metadata_error())
}

fn response_metadata_from_observation(
    observed: &ObservedResponseState,
    expect_context_editing: bool,
    expect_cache_usage: bool,
) -> Result<AnthropicResponseMetadata, LlmError> {
    let context_editing = if expect_context_editing {
        let context = observed
            .context_management
            .clone()
            .ok_or_else(metadata_error)?;
        Some(
            AnthropicContextEditReport::from_terminal(
                &serde_json::json!({"context_management":context}),
            )
            .map_err(|_| metadata_error())?,
        )
    } else {
        None
    };
    let cache_usage = if expect_cache_usage {
        Some(
            AnthropicCacheUsage::from_usage(observed.usage.as_ref().ok_or_else(metadata_error)?)
                .map_err(|_| metadata_error())?,
        )
    } else {
        None
    };
    Ok(AnthropicResponseMetadata::new(context_editing, cache_usage))
}

fn compaction_resolve_error(error: AnthropicCompactionFault, model: &str) -> ResolveError {
    match error {
        AnthropicCompactionFault::UnsupportedCapability => ResolveError::Unsupported {
            provider: ANTHROPIC_PROVIDER.to_owned(),
            model: model.to_owned(),
            capability: heycode_llm::RequestedCapability::NativeCompaction,
        },
        AnthropicCompactionFault::UnprovenCapability => ResolveError::Unproven {
            provider: ANTHROPIC_PROVIDER.to_owned(),
            model: model.to_owned(),
            capability: heycode_llm::RequestedCapability::NativeCompaction,
        },
        AnthropicCompactionFault::InvalidConfiguration
        | AnthropicCompactionFault::WrongRoute
        | AnthropicCompactionFault::InvalidState => ResolveError::InvalidRequest {
            field: "native_features",
            message: "Anthropic native compaction configuration is invalid".to_owned(),
        },
    }
}

fn server_tool_configuration_error(error: AnthropicServerToolFault) -> LlmError {
    LlmError::InvalidResponse(error.to_string())
}

fn server_tool_resolve_error(error: AnthropicServerToolFault, model: &str) -> ResolveError {
    match error {
        AnthropicServerToolFault::UnsupportedCapability => ResolveError::Unsupported {
            provider: ANTHROPIC_PROVIDER.to_owned(),
            model: model.to_owned(),
            capability: heycode_llm::RequestedCapability::Tools,
        },
        AnthropicServerToolFault::UnprovenCapability => ResolveError::Unproven {
            provider: ANTHROPIC_PROVIDER.to_owned(),
            model: model.to_owned(),
            capability: heycode_llm::RequestedCapability::Tools,
        },
        AnthropicServerToolFault::InvalidConfiguration
        | AnthropicServerToolFault::WrongRoute
        | AnthropicServerToolFault::InvalidState => ResolveError::InvalidRequest {
            field: "provider_options",
            message: "Anthropic server-tool configuration is invalid".to_owned(),
        },
    }
}

fn map_native_compaction_error(
    error: &LlmError,
    cancellation: &tokio_util::sync::CancellationToken,
) -> NativeCompactionError {
    if cancellation.is_cancelled() || error.class() == ProviderErrorClass::Cancelled {
        NativeCompactionError::Cancelled
    } else {
        match error.class() {
            ProviderErrorClass::Protocol | ProviderErrorClass::Overflow => {
                NativeCompactionError::InvalidCheckpoint
            }
            ProviderErrorClass::Authentication
            | ProviderErrorClass::ContextWindowExceeded
            | ProviderErrorClass::Conflict
            | ProviderErrorClass::InvalidRequest => NativeCompactionError::Rejected,
            ProviderErrorClass::RateLimited
            | ProviderErrorClass::Overloaded
            | ProviderErrorClass::Server
            | ProviderErrorClass::Timeout
            | ProviderErrorClass::Network => NativeCompactionError::Transport,
            ProviderErrorClass::Cancelled => NativeCompactionError::Cancelled,
        }
    }
}

fn metadata_error() -> LlmError {
    LlmError::InvalidResponse("Anthropic response metadata is invalid".to_owned())
}

fn one_inference_error(error: LlmError) -> InferenceStream {
    Box::pin(futures::stream::once(async move { Err(error) }))
}

fn resolve_to_llm(error: ResolveError) -> LlmError {
    LlmError::InvalidResponse(error.to_string())
}
