#!/usr/bin/env python3
"""Generate checked-in heycode reference pages from Rust source contracts.

The generator is intentionally standard-library-only.  It does not execute the
product or contact a provider.  Each parser is narrow and fails when the source
shape it consumes changes, turning descriptor drift into an explicit docs task.
"""

from __future__ import annotations

import argparse
import hashlib
import re
import sys
from dataclasses import dataclass
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]

COMMAND_PROJECTION = Path("crates/heycode-cli/tests/it/composition.rs")
CONFIG_SOURCE = Path("crates/heycode-config/src/lib.rs")
CONFIG_MIGRATION_SOURCE = Path("crates/heycode-config/src/migration.rs")
PROFILE_SOURCE = Path("crates/heycode-config/src/profiles.rs")
INVENTORY_PROJECTION = Path("crates/heycode-cli/tests/it/plugin_inventory.rs")
COMPOSITION_SOURCE = Path("crates/heycode-cli/src/lib.rs")
CORE_DESCRIPTOR_SOURCE = Path("crates/heycode-core/src/descriptor.rs")
CORE_INVENTORY_SOURCE = Path("crates/heycode-core/src/inventory.rs")
MANIFEST_WIRE_SOURCE = Path("crates/heycode-extensions/src/wire.rs")
MANIFEST_MODEL_SOURCE = Path("crates/heycode-extensions/src/model.rs")
MANIFEST_FIXTURE = Path("crates/heycode-extensions/tests/fixtures/plugin-v1.toml")
SESSION_EVENT_SOURCE = Path("crates/heycode-session/src/event.rs")

OUTPUTS = {
    Path("docs/reference/commands.md"),
    Path("docs/reference/configuration.md"),
    Path("docs/reference/plugins.md"),
    Path("docs/reference/session-events.md"),
}


class GenerationError(RuntimeError):
    """A source contract no longer has the shape this generator understands."""


@dataclass(frozen=True)
class Field:
    """One documented Rust struct field."""

    name: str
    rust_type: str
    docs: str


@dataclass(frozen=True)
class CommandRow:
    """One command descriptor projected by real composition."""

    command_id: str
    timing: str
    owner: str
    synopsis: str
    description: str


def read(path: Path) -> str:
    """Read one repository-relative UTF-8 source."""

    try:
        return (ROOT / path).read_text(encoding="utf-8")
    except OSError as error:
        raise GenerationError(f"cannot read {path}: {error}") from error


def source_digest(paths: list[Path]) -> str:
    """Digest source paths and bytes so the generated provenance is inspectable."""

    digest = hashlib.sha256()
    for path in sorted(paths, key=lambda item: item.as_posix()):
        digest.update(path.as_posix().encode("utf-8"))
        digest.update(b"\0")
        digest.update(read(path).encode("utf-8"))
        digest.update(b"\0")
    return digest.hexdigest()


def generated_header(title: str, sources: list[Path]) -> str:
    """Common generated-file preamble."""

    source_lines = "\n".join(f"- `{path.as_posix()}`" for path in sources)
    return (
        "<!-- GENERATED by scripts/generate_doc_references.py. Do not edit by hand. -->\n"
        f"# {title}\n\n"
        "This page is generated from current Rust contracts. Regenerate with "
        "`python3 scripts/verify_docs.py --write`; verify with "
        "`python3 scripts/verify_docs.py`.\n\n"
        f"Source digest: `{source_digest(sources)}`\n\n"
        "Sources:\n\n"
        f"{source_lines}\n\n"
    )


def rust_string(value: str) -> str:
    """Decode the small escaped-string subset used by descriptor literals."""

    return (
        value.replace(r"\\", "\0")
        .replace(r'\"', '"')
        .replace(r"\n", "\n")
        .replace(r"\t", "\t")
        .replace("\0", "\\")
    )


def source_rs_files() -> list[Path]:
    """Production Rust sources that can own command descriptors."""

    return sorted(
        path.relative_to(ROOT)
        for path in (ROOT / "crates").glob("*/src/**/*.rs")
        if path.is_file()
    )


def command_descriptor_files() -> list[Path]:
    """Production files that construct literal command descriptors."""

    files: list[Path] = []
    for path in source_rs_files():
        text = read(path)
        if "CommandDescriptor::new" in text or re.search(r'\bdescriptor\(\s*"', text):
            files.append(path)
    return files


def command_descriptions() -> dict[str, str]:
    """Extract literal command descriptions from production descriptor calls."""

    descriptions: dict[str, str] = {}
    direct = re.compile(
        r"(?:CommandDescriptor::new|\bdescriptor)\(\s*"
        r'"(?P<id>[a-z0-9-]+)"\s*,\s*'
        r'"(?P<description>(?:[^"\\]|\\.)*)"',
        re.DOTALL,
    )
    session_row = re.compile(
        r"SessionCommandKind::[A-Za-z]+\s*,\s*"
        r'"(?P<id>[a-z0-9-]+)"\s*,\s*'
        r'"(?P<description>(?:[^"\\]|\\.)*)"',
        re.DOTALL,
    )
    human_row = re.compile(
        r"\(\s*"
        r'"(?P<id>[a-z0-9-]+)"\s*,\s*'
        r'"(?P<description>(?:[^"\\]|\\.)*)"\s*,\s*'
        r"HumanOnlyKind::[A-Za-z]+\s*,?\s*\)",
        re.DOTALL,
    )
    inspection_row = re.compile(
        r'\(\s*"(?P<id>[a-z0-9-]+)"\s*,\s*'
        r'"[a-z0-9-]+"\s*,\s*'
        r'"(?P<description>(?:[^"\\]|\\.)*)"\s*,?\s*\)',
        re.DOTALL,
    )
    feature_row = re.compile(
        r'\(\s*"(?P<id>[a-z0-9-]+)"\s*,\s*'
        r'"(?P<description>(?:[^"\\]|\\.)*)"\s*,\s*'
        r'"[a-z0-9-]+"\s*,?\s*\)',
        re.DOTALL,
    )
    recompose_row = re.compile(
        r'\(\s*"(?P<id>[a-z0-9-]+)"\s*,\s*'
        r'"(?P<description>(?:[^"\\]|\\.)*)"\s*,\s*'
        r'(?:true|false)\s*,?\s*\)', re.DOTALL,
    )
    background_row = re.compile(
        r'\(\s*"(?P<id>[a-z0-9-]+)"\s*,\s*'
        r'"(?P<description>(?:[^"\\]|\\.)*)"\s*,\s*'
        r'Kind::[A-Za-z]+\s*,\s*CommandTiming::[A-Za-z]+\s*,?\s*\)', re.DOTALL,
    )
    workspace_row = re.compile(
        r'WorkspaceCommandKind::[A-Za-z]+\s*=>\s*\(\s*'
        r'"(?P<id>[a-z0-9-]+)"\s*,\s*'
        r'"(?P<description>(?:[^"\\]|\\.)*)"\s*,', re.DOTALL,
    )
    for path in command_descriptor_files():
        # Test-only descriptors can reuse production IDs with fixture labels.
        text = without_test_modules(read(path))
        patterns = [direct, session_row]
        if path == Path("crates/heycode-agent/src/session_control.rs"):
            patterns.append(feature_row)
        if path.name == "human_commands.rs":
            patterns.extend([human_row, inspection_row])
        if path.name == "recomposition.rs":
            patterns.append(recompose_row)
        if path.name == "session_background.rs":
            patterns.append(background_row)
        if path.name == "workspace_integration.rs":
            patterns.append(workspace_row)
        for pattern in patterns:
            for match in pattern.finditer(text):
                command_id = match.group("id")
                description = rust_string(match.group("description"))
                previous = descriptions.get(command_id)
                if previous is not None and previous != description:
                    raise GenerationError(
                        f"conflicting descriptions for /{command_id}: "
                        f"{previous!r} vs {description!r}"
                    )
                descriptions[command_id] = description
        if path.name == "panel_commands.rs" and "enum CapabilityPanel" in text:
            ids = dict(
                re.findall(
                    r'Self::([A-Za-z0-9_]+)\s*=>\s*"([a-z0-9-]+)"',
                    balanced_body(text, "pub const fn as_str"),
                )
            )
            panel_descriptions = dict(
                re.findall(
                    r'Self::([A-Za-z0-9_]+)\s*=>\s*"((?:[^"\\]|\\.)*)"',
                    balanced_body(text, "pub const fn description"),
                )
            )
            if set(ids) != set(panel_descriptions):
                raise GenerationError("CapabilityPanel id/description tables drifted")
            commanded_start = text.find("const COMMANDED_PANELS")
            commanded_end = text.find("];", commanded_start)
            if commanded_start < 0 or commanded_end < 0:
                raise GenerationError("CapabilityPanel commanded set changed shape")
            commanded = set(
                re.findall(
                    r"CapabilityPanel::([A-Za-z0-9_]+)",
                    text[commanded_start:commanded_end],
                )
            )
            for variant in commanded:
                command_id = ids[variant]
                description = rust_string(panel_descriptions[variant])
                previous = descriptions.get(command_id)
                if previous is not None and previous != description:
                    raise GenerationError(
                        f"conflicting descriptions for /{command_id}: "
                        f"{previous!r} vs {description!r}"
                    )
                descriptions[command_id] = description
    return descriptions


def parse_command_rows() -> list[CommandRow]:
    """Parse the exact catalog tuple asserted against real composition."""

    text = read(COMMAND_PROJECTION)
    start_marker = "let command_catalog = commands.catalog().unwrap();"
    end_marker = "for entry in &command_catalog"
    try:
        block = text[text.index(start_marker) : text.index(end_marker, text.index(start_marker))]
    except ValueError as error:
        raise GenerationError("command catalog projection markers changed") from error
    tuple_pattern = re.compile(
        r"\(\s*"
        r'"(?P<id>[a-z0-9-]+)"\s*,\s*'
        r'"(?P<timing>[a-z_]+)"\s*,\s*'
        r'"(?P<owner>[a-z0-9-]+)"\s*,\s*'
        r'"(?P<synopsis>/[^"\n]+)"\.to_owned\(\)\s*,?\s*\)',
        re.DOTALL,
    )
    projected = [match.groupdict() for match in tuple_pattern.finditer(block)]
    if len(projected) < 20:
        raise GenerationError(
            f"expected a complete command catalog projection, found {len(projected)} rows"
        )
    descriptions = command_descriptions()
    rows: list[CommandRow] = []
    seen: set[str] = set()
    for row in projected:
        command_id = row["id"]
        if command_id in seen:
            raise GenerationError(f"duplicate generated command id {command_id}")
        seen.add(command_id)
        description = descriptions.get(command_id)
        if description is None:
            raise GenerationError(f"no production descriptor description found for /{command_id}")
        rows.append(
            CommandRow(
                command_id=command_id,
                timing=row["timing"],
                owner=row["owner"],
                synopsis=row["synopsis"],
                description=description,
            )
        )
    return rows


def render_commands() -> str:
    """Render the command catalog reference."""

    sources = [
        COMMAND_PROJECTION,
        Path("crates/heycode-agent/src/command_descriptor.rs"),
        *command_descriptor_files(),
    ]
    rows = parse_command_rows()
    table = [
        "| Command | Purpose | Active-turn timing | Owner |",
        "|---|---|---|---|",
    ]
    for row in rows:
        table.append(
            f"| `{row.synopsis}` | {row.description} | `{row.timing}` | `{row.owner}` |"
        )
    return (
        generated_header("Command reference", sources)
        + "The table follows the default real-composition catalog order. Command "
        "availability is dynamic: a row can remain discoverable but unavailable when its "
        "service or runtime prerequisite is absent. Slash commands are human-plane actions; "
        "they do not become model messages unless a command explicitly schedules a model turn.\n\n"
        + "\n".join(table)
        + "\n\n## Timing vocabulary\n\n"
        + "- `immediate`: may run while a turn is active.\n"
        + "- `queued`: waits for active work to settle.\n"
        + "- `interrupting`: requires confirmation and cancellation before it runs.\n"
        + "- `model_scheduling`: changes durable domain state and may start logged model work.\n\n"
        + "For top-level management commands (`heycode mcp`, `heycode plugin`, `heycode doctor`), "
        + "use the corresponding user guides; they are CLI operations rather than slash-command rows.\n"
        + "\nSee [session behavior and evidence](../guides/session-behavior.md) for context accounting, structured work, team lifecycle, and background handoff details.\n"
    )


def without_test_modules(text: str) -> str:
    """Remove test modules while retaining production items that follow them."""

    module = re.compile(
        r"#\[cfg\(test\)\]\s*(?:#\[[^\]]*\]\s*)*mod\s+[A-Za-z_][A-Za-z0-9_]*\s*"
    )
    while match := module.search(text):
        opening = text.find("{", match.end())
        body = balanced_body(text[match.start():], match.group())
        end = opening + len(body) + 2
        text = text[:match.start()] + "\n" + text[end:]
    return text


def balanced_body(text: str, marker: str) -> str:
    """Return the brace body following marker, ignoring braces in strings/comments."""

    marker_index = text.find(marker)
    if marker_index < 0:
        raise GenerationError(f"cannot find source marker {marker!r}")
    opening = text.find("{", marker_index + len(marker))
    if opening < 0:
        raise GenerationError(f"source marker {marker!r} has no body")
    depth = 0
    in_string = False
    escaped = False
    in_line_comment = False
    for index in range(opening, len(text)):
        char = text[index]
        next_char = text[index + 1] if index + 1 < len(text) else ""
        if in_line_comment:
            if char == "\n":
                in_line_comment = False
            continue
        if in_string:
            if escaped:
                escaped = False
            elif char == "\\":
                escaped = True
            elif char == '"':
                in_string = False
            continue
        if char == "/" and next_char == "/":
            in_line_comment = True
            continue
        if char == '"':
            in_string = True
            continue
        if char == "{":
            depth += 1
        elif char == "}":
            depth -= 1
            if depth == 0:
                return text[opening + 1 : index]
    raise GenerationError(f"unterminated source body for {marker!r}")


def parse_struct_fields(text: str, name: str) -> list[Field]:
    """Parse documented public fields from one simple Rust struct."""

    body = balanced_body(text, f"struct {name}")
    fields: list[Field] = []
    docs: list[str] = []
    for raw_line in body.splitlines():
        line = raw_line.strip()
        if line.startswith("///"):
            docs.append(line[3:].strip())
            continue
        if not line or line.startswith("#["):
            continue
        match = re.match(r"pub(?:\(crate\))?\s+(\w+)\s*:\s*(.+),$", line)
        if match:
            fields.append(
                Field(
                    name=match.group(1),
                    rust_type=match.group(2).strip(),
                    docs=" ".join(docs),
                )
            )
            docs = []
            continue
        docs = []
    if not fields:
        raise GenerationError(f"no public fields parsed from {name}")
    return fields


def parse_constants(text: str) -> dict[str, str]:
    """Parse scalar/string public constants used by defaults."""

    constants: dict[str, str] = {}
    for match in re.finditer(
        r"pub const (?P<name>[A-Z0-9_]+)\s*:\s*[^=]+\s*=\s*(?P<value>[^;]+);", text
    ):
        value = match.group("value").strip()
        if value.startswith('"') and value.endswith('"'):
            value = value[1:-1]
        constants[match.group("name")] = value
    return constants


def parse_default_expressions(text: str, name: str) -> dict[str, str]:
    """Parse direct fields of one `impl Default` struct literal."""

    marker = f"impl Default for {name}"
    if marker not in text:
        return {}
    body = balanced_body(text, marker)
    self_index = body.find("Self")
    if self_index < 0:
        return {}
    literal = balanced_body(body, "Self")
    return {
        match.group(1): match.group(2).strip()
        for match in re.finditer(r"\b(\w+)\s*:\s*([^,\n}]+)", literal)
    }


def parse_default_enum(text: str, name: str) -> str | None:
    """Find the variant immediately following `#[default]`."""

    body = balanced_body(text, f"enum {name}")
    match = re.search(r"#\[default\]\s*([A-Za-z0-9_]+)", body)
    return match.group(1) if match else None


def enum_values(text: str, name: str, style: str = "snake_case") -> list[str]:
    """Parse simple enum variants and apply serde's naming convention."""

    body = balanced_body(text, f"enum {name}")
    values: list[str] = []
    for line in body.splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith(("///", "#[", "//")):
            continue
        match = re.match(r"([A-Z][A-Za-z0-9_]+)(?:\s*\{|\s*,)", stripped)
        if not match:
            continue
        variant = match.group(1)
        if style == "lowercase":
            values.append(variant.lower())
        else:
            values.append(re.sub(r"(?<!^)(?=[A-Z])", "_", variant).lower())
    if not values:
        raise GenerationError(f"no enum values parsed from {name}")
    return values


def friendly_type(config_text: str, rust_type: str) -> str:
    """Render a compact user-facing type from a Rust field type."""

    compact = rust_type.replace("std::collections::", "")
    aliases = {
        "String": "string",
        "bool": "boolean",
        "u32": "integer",
        "u64": "integer",
        "usize": "integer",
        "f32": "number",
        "Option<String>": "string or omitted",
        "Vec<String>": "array of strings",
        "HashMap<String, String>": "map of strings",
    }
    if compact in aliases:
        return aliases[compact]
    if compact in {"ApprovalMode", "SandboxModeCfg"}:
        style = "lowercase"
        return "`" + " | ".join(enum_values(config_text, compact, style)) + "`"
    if compact.startswith("HashMap<String, McpServerCfg>"):
        return "map of server tables"
    return f"`{compact}`"


def default_value(
    config_text: str,
    constants: dict[str, str],
    struct_name: str,
    field: Field,
) -> str:
    """Resolve a field default from its Rust `Default` contract."""

    explicit = parse_default_expressions(config_text, struct_name).get(field.name)
    if explicit is not None:
        constant_match = re.fullmatch(r"([A-Z0-9_]+)\.to_owned\(\)", explicit)
        if constant_match:
            return f"`{constants[constant_match.group(1)]}`"
        if explicit in {"true", "false"}:
            return f"`{explicit}`"
        if re.fullmatch(r"[0-9_]+(?:\.[0-9_]+)?", explicit):
            return f"`{explicit.replace('_', '')}`"
        if explicit == "None":
            return "omitted"
        return f"`{explicit}`"
    rust_type = field.rust_type.replace("std::collections::", "")
    if rust_type.startswith("Option<"):
        return "omitted"
    if rust_type.startswith(("Vec<", "HashMap<")):
        return "empty"
    if rust_type == "bool":
        return "`false`"
    if rust_type in {"ApprovalMode", "SandboxModeCfg"}:
        variant = parse_default_enum(config_text, rust_type)
        if variant is None:
            raise GenerationError(f"{rust_type} has no #[default] variant")
        return f"`{variant.lower()}`"
    raise GenerationError(f"cannot resolve default for {struct_name}.{field.name}")


def parse_settings_namespaces() -> list[tuple[str, str]]:
    """Parse exact Settings namespace ownership from the composition inventory gate."""

    text = read(INVENTORY_PROJECTION)
    pattern = re.compile(
        r"\(\s*"
        r'"(?P<owner>[a-z0-9-]+)"\s*,\s*'
        r"heycode_core::ContributionKind::SettingsNamespace\s*,\s*"
        r'"(?P<namespace>[a-z0-9-]+)"\s*,?\s*\)',
        re.DOTALL,
    )
    rows = [(match.group("namespace"), match.group("owner")) for match in pattern.finditer(text)]
    if len(rows) < 5:
        raise GenerationError(f"expected Settings namespace inventory, found {len(rows)} rows")
    if len({namespace for namespace, _ in rows}) != len(rows):
        raise GenerationError("duplicate Settings namespace in documentation projection")
    return rows


def render_configuration() -> str:
    """Render root configuration and live Settings namespace references."""

    sources = [CONFIG_SOURCE, CONFIG_MIGRATION_SOURCE, PROFILE_SOURCE, INVENTORY_PROJECTION]
    text = read(CONFIG_SOURCE)
    constants = parse_constants(text)
    migration = read(CONFIG_MIGRATION_SOURCE)
    schema_match = re.search(r"pub const CONFIG_SCHEMA_VERSION: u32 = (\d+);", migration)
    if schema_match is None:
        raise GenerationError("CONFIG_SCHEMA_VERSION declaration changed")
    root_fields = parse_struct_fields(text, "Config")
    section_types = {
        field.name: field.rust_type
        for field in root_fields
        if field.name != "schema_version"
    }
    expected_sections = {
        "profile",
        "llm",
        "tools",
        "ui",
        "approval",
        "compaction",
        "subagent",
        "jobs",
        "sandbox",
        "web",
        "mcp",
    }
    if set(section_types) != expected_sections:
        raise GenerationError(
            "Config section set changed: "
            f"expected {sorted(expected_sections)}, found {sorted(section_types)}"
        )
    table = [
        "| Path | Type | Default | Contract |",
        "|---|---|---|---|",
    ]
    for section, struct_name in section_types.items():
        for field in parse_struct_fields(text, struct_name):
            path = f"{section}.{field.name}"
            if section == "mcp" and field.name == "servers":
                table.append(
                    "| `mcp.servers.<name>` | map of server tables | empty | "
                    "Each name selects exactly one stdio or Streamable HTTP transport. |"
                )
                continue
            table.append(
                f"| `{path}` | {friendly_type(text, field.rust_type)} | "
                f"{default_value(text, constants, struct_name, field)} | {field.docs} |"
            )
    mcp_rows = [
        "| Key | Type | Default | Contract |",
        "|---|---|---|---|",
    ]
    for field in parse_struct_fields(text, "McpServerCfg"):
        mcp_rows.append(
            f"| `{field.name}` | {friendly_type(text, field.rust_type)} | "
            f"{default_value(text, constants, 'McpServerCfg', field)} | {field.docs} |"
        )
    settings_rows = [
        "| Namespace | Owning plugin |",
        "|---|---|",
    ]
    for namespace, owner in parse_settings_namespaces():
        settings_rows.append(f"| `{namespace}` | `{owner}` |")
    profile_schema_match = re.search(
        r"pub const PROFILE_SCHEMA_VERSION: u32 = (\d+);", read(PROFILE_SOURCE)
    )
    if profile_schema_match is None:
        raise GenerationError("PROFILE_SCHEMA_VERSION declaration changed")
    return (
        generated_header("Configuration reference", sources)
        + f"The current root TOML schema is **{schema_match.group(1)}**. Discovery is "
        "`--config` → trusted `./heycode.toml` → absolute `$HEYCODE_HOME/config.toml` → "
        "built-in defaults. A relative `HEYCODE_HOME`, unknown field/path, malformed type, "
        "or newer schema fails loud.\n\n"
        + "## Root `heycode.toml`\n\n"
        + "\n".join(table)
        + "\n\n`[profile].plugins` is an exact ordered override. Leave it absent or empty to "
        "track the built-in profile; a frozen list does not gain future plugins automatically.\n\n"
        + "## MCP server table\n\n"
        + "Under `[mcp.servers.<name>]`, choose exactly one of `command` and `url`. "
        "`args` and `env` are valid only with `command`.\n\n"
        + "\n".join(mcp_rows)
        + "\n\n## Plugin Settings namespaces\n\n"
        + "The rows below are generated from exact composition inventory. Their field schemas "
        "are registered at runtime and rendered by `/settings`; they are not duplicated into "
        "this static page. Values live in `$HEYCODE_HOME/settings.toml` under "
        "`[settings.<namespace>]` and use revision/CAS publication.\n\n"
        + "\n".join(settings_rows)
        + "\n\n## Named profiles\n\n"
        + f"The current standalone profile schema is **{profile_schema_match.group(1)}** at "
        "`$HEYCODE_HOME/profiles/<name>.toml`. Profiles contain ordered "
        "`[[plugins]]` rows with `id` and `enabled`; schema v2 also permits managed-only "
        "constraints. `--profile <name>` and `/profile` share the same strict store.\n\n"
        + "Credential values never belong in root config, profiles, Settings, generated "
        "references, or examples. These surfaces retain non-secret references only.\n"
    )


def parse_string_array(text: str, marker: str) -> list[str]:
    """Parse a Rust `&[&str]`/array literal following marker."""

    marker_index = text.find(marker)
    if marker_index < 0:
        raise GenerationError(f"cannot find array marker {marker!r}")
    opening = text.find("[", marker_index + len(marker))
    closing = text.find("];", opening)
    if opening < 0 or closing < 0:
        raise GenerationError(f"unterminated array for {marker!r}")
    values = re.findall(r'"([^"\n]+)"', text[opening:closing])
    if not values:
        raise GenerationError(f"empty array for {marker!r}")
    return values


def parse_match_ids(text: str, enum_name: str) -> list[str]:
    """Parse stable `Self::Variant => \"id\"` values from an enum impl."""

    marker = f"impl {enum_name}"
    body = balanced_body(text, marker)
    values = re.findall(r'Self::[A-Za-z0-9_]+\s*=>\s*"([a-z0-9_]+)"', body)
    if not values:
        raise GenerationError(f"no stable ids parsed for {enum_name}")
    return values


def wire_type(rust_type: str) -> tuple[str, str]:
    """Render manifest-wire type and requiredness."""

    required = "optional" if rust_type.startswith("Option<") else "required"
    display = rust_type.replace("Wire", "").replace("String", "string")
    display = re.sub(r"Vec<([^>]+)>", r"array<\1>", display)
    display = re.sub(r"Option<([^>]+)>", r"\1", display)
    return display, required


def render_plugins() -> str:
    """Render built-in order, descriptor vocabulary, and manifest-v1 schema."""

    sources = [
        COMPOSITION_SOURCE,
        CORE_DESCRIPTOR_SOURCE,
        CORE_INVENTORY_SOURCE,
        MANIFEST_WIRE_SOURCE,
        MANIFEST_MODEL_SOURCE,
        MANIFEST_FIXTURE,
    ]
    composition = read(COMPOSITION_SOURCE)
    order = parse_string_array(composition, "pub const BUILTIN_PLUGIN_ORDER")
    descriptor_text = read(CORE_DESCRIPTOR_SOURCE)
    inventory_text = read(CORE_INVENTORY_SOURCE)
    broad = parse_match_ids(descriptor_text, "PluginContributionKind")
    exact = parse_match_ids(inventory_text, "ContributionKind")
    order_rows = ["| Position | Plugin id |", "|---:|---|"]
    order_rows.extend(f"| {index} | `{plugin}` |" for index, plugin in enumerate(order, 1))
    manifest_text = read(MANIFEST_WIRE_SOURCE)
    manifest_rows = ["| Field | Wire type | Presence |", "|---|---|---|"]
    for field in parse_struct_fields(manifest_text, "WireManifest"):
        display, required = wire_type(field.rust_type)
        manifest_rows.append(f"| `{field.name}` | `{display}` | {required} |")
    model_text = read(MANIFEST_MODEL_SOURCE)
    enum_sets = [
        ("Contribution kinds", "ContributionKind", "snake_case"),
        ("Requested permissions", "PluginPermission", "snake_case"),
        ("Operating systems", "OperatingSystem", "snake_case"),
        ("Architectures", "Architecture", "snake_case"),
        ("Authentication policy", "AuthenticationPolicy", "snake_case"),
        ("Source kinds", "PluginSourceKind", "snake_case"),
        ("Signature algorithms", "SignatureAlgorithm", "snake_case"),
        ("Update channels", "UpdateChannel", "snake_case"),
    ]
    vocab_rows = ["| Vocabulary | Accepted values |", "|---|---|"]
    for label, enum_name, style in enum_sets:
        values = enum_values(model_text, enum_name, style)
        vocab_rows.append(f"| {label} | " + ", ".join(f"`{value}`" for value in values) + " |")
    fixture = read(MANIFEST_FIXTURE).rstrip()
    return (
        generated_header("Plugin reference", sources)
        + "## Built-in composition candidates\n\n"
        + "This is the composition root's ordered candidate list before availability "
        "filtering. A candidate is applied only when its factory is registered for the "
        "current platform, route, profile, and managed policy. Use `/plugins verbose` or "
        "`heycode doctor --composition --json` for the exact live world.\n\n"
        + "\n".join(order_rows)
        + "\n\n## Descriptor and inventory vocabulary\n\n"
        + "Broad descriptor families: "
        + ", ".join(f"`{value}`" for value in broad)
        + ".\n\nExact inventory namespaces: "
        + ", ".join(f"`{value}`" for value in exact)
        + ".\n\nBroad families state what a plugin may contribute. Exact inventory states "
        "which named service, command, tool, provider, process, or other row a committed "
        "activation actually owns.\n\n"
        + "## External plugin manifest v1\n\n"
        + "The manifest is strict (`deny_unknown_fields`). Fields classified optional are "
        "the only fields whose Rust wire type is `Option`; arrays remain required even when empty.\n\n"
        + "\n".join(manifest_rows)
        + "\n\n### Closed manifest vocabulary\n\n"
        + "\n".join(vocab_rows)
        + "\n\n### Canonical validated fixture\n\n"
        + "```toml\n"
        + fixture
        + "\n```\n\n"
        + "A manifest proves validated metadata, not installation, signature validity, "
        "activation, or product reachability. Managed admission and lifecycle state remain "
        "separate commit gates.\n"
    )


def parse_session_contracts() -> tuple[list[str], list[str], dict[str, str]]:
    """Parse closed kind lists and enum documentation."""

    text = read(SESSION_EVENT_SOURCE)
    v1 = parse_string_array(text, "KNOWN_KINDS_V1")
    v2 = parse_string_array(text, "KNOWN_KINDS_V2")
    body = balanced_body(text, "enum SessionEventKind")
    docs_by_tag: dict[str, str] = {}
    docs: list[str] = []
    pending_tag: str | None = None
    for raw_line in body.splitlines():
        line = raw_line.strip()
        if line.startswith("///"):
            docs.append(line[3:].strip())
            continue
        rename = re.match(r'#\[serde\(rename = "([^"]+)"\)\]', line)
        if rename:
            pending_tag = rename.group(1)
            continue
        if pending_tag is not None and re.match(r"[A-Z][A-Za-z0-9_]+", line):
            summary = " ".join(docs).strip()
            if not summary:
                raise GenerationError(f"session kind {pending_tag} has no documentation")
            docs_by_tag[pending_tag] = summary
            pending_tag = None
            docs = []
            continue
        if line and not line.startswith("#["):
            docs = []
    if set(docs_by_tag) != set(v2):
        missing = sorted(set(v2) - set(docs_by_tag))
        extra = sorted(set(docs_by_tag) - set(v2))
        raise GenerationError(f"session kind/doc drift: missing={missing}, extra={extra}")
    if not set(v1).issubset(v2):
        raise GenerationError("v1 kind set is not a subset of v2")
    return v1, v2, docs_by_tag


def render_session_events() -> str:
    """Render the closed session event vocabulary."""

    sources = [SESSION_EVENT_SOURCE]
    text = read(SESSION_EVENT_SOURCE)
    v1, v2, docs = parse_session_contracts()
    rows = ["| Kind | Readable envelope versions | Payload role |", "|---|---|---|"]
    for tag in v2:
        versions = "v1, v2" if tag in v1 else "v2 only"
        rows.append(f"| `{tag}` | {versions} | {docs[tag]} |")
    reasons = enum_values(text, "TurnEndReason", "snake_case")
    min_match = re.search(r"MIN_SESSION_LOG_VERSION: u8 = (\d+);", text)
    current_match = re.search(r"CURRENT_SESSION_LOG_VERSION: u8 = (\d+);", text)
    if min_match is None or current_match is None:
        raise GenerationError("session version constants changed")
    return (
        generated_header("Session event reference", sources)
        + f"This reader accepts envelope versions **{min_match.group(1)} through "
        f"{current_match.group(1)}**. New appends always use the current version; opening a "
        "historical log preserves its original bytes. Unknown kinds fail loud.\n\n"
        + "\n".join(rows)
        + "\n\n## Turn settlement reasons\n\n"
        + ", ".join(f"`{reason}`" for reason in reasons)
        + ".\n\n"
        + "This page enumerates wire vocabulary, not model visibility. Route-aware request "
        "projection decides which neutral messages, exact provider state, attachments, and "
        "compaction checkpoint form a particular request.\n"
    )


def render_all() -> dict[Path, str]:
    """Render every generated reference exactly once."""

    rendered = {
        Path("docs/reference/commands.md"): render_commands(),
        Path("docs/reference/configuration.md"): render_configuration(),
        Path("docs/reference/plugins.md"): render_plugins(),
        Path("docs/reference/session-events.md"): render_session_events(),
    }
    if set(rendered) != OUTPUTS:
        raise GenerationError("generated output registry drift")
    return rendered


def write_all(rendered: dict[Path, str]) -> None:
    """Write rendered references."""

    for path, content in rendered.items():
        destination = ROOT / path
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_text(content, encoding="utf-8")


def check_all(rendered: dict[Path, str]) -> list[str]:
    """Return stale/missing outputs without mutating the tree."""

    stale: list[str] = []
    for path, content in rendered.items():
        destination = ROOT / path
        try:
            current = destination.read_text(encoding="utf-8")
        except OSError:
            stale.append(f"missing {path}")
            continue
        if current != content:
            stale.append(f"stale {path}")
    return stale


def main() -> int:
    """CLI entry point."""

    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true", help="regenerate checked-in references")
    mode.add_argument("--check", action="store_true", help="fail when references are stale")
    args = parser.parse_args()
    try:
        rendered = render_all()
        if args.write:
            write_all(rendered)
            for path in sorted(rendered, key=lambda item: item.as_posix()):
                print(f"generated {path}")
            return 0
        stale = check_all(rendered)
        if stale:
            for item in stale:
                print(item, file=sys.stderr)
            print(
                "regenerate with python3 scripts/generate_doc_references.py --write",
                file=sys.stderr,
            )
            return 1
        print(f"generated references fresh: {len(rendered)}")
        return 0
    except GenerationError as error:
        print(f"documentation generation failed: {error}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
