[package]
name = "heycode-tools"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
heycode-core = { workspace = true }
heycode-exec = { workspace = true }
heycode-native-tools = { workspace = true }
heycode-web = { workspace = true }
heycode-attachments = { workspace = true }
anyhow = { workspace = true }
async-trait = { workspace = true }
serde_json = { workspace = true }
serde = { workspace = true }
sha2 = { workspace = true }
base64 = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
url = { workspace = true }

[dev-dependencies]
heycode-sandbox = { workspace = true }
tempfile = { workspace = true }

[lints]
workspace = true
