[package]
name = "heycode-exec"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
heycode-core = { workspace = true }
async-trait = { workspace = true }
cap-std = { workspace = true }
futures = { workspace = true }
processkit = { workspace = true, features = ["pty"] }
regex = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
uuid = { workspace = true }
url = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }

[lints]
workspace = true
